name: Build, Analyze, Scan

on:
  push:
    branches:
      - main

jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures full repo history for better analysis

      - name: Stop and remove existing container (if exists)
        run: |
          docker ps -q --filter "name=game" | grep -q . && docker stop game && docker rm game || echo "No existing container to remove"

      - name: Update kubeconfig
        run: aws eks --region af-south-1 update-kubeconfig --name EKS_CLOUD

      - name: Remove Kubernetes Deployment (if exists)
        run: |
          kubectl get -f deployment-service.yml && kubectl delete -f deployment-service.yml || echo "Deployment not found, skipping delete"

      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubactions-and-kubernetes'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
